// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Customer.Orders
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class CustomerOrder : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""CustomerOrder"",""namespace"":""Customer.Orders"",""fields"":[{""name"":""orderNumber"",""type"":""string""},{""name"":""status"",""type"":""string""},{""name"":""orderItems"",""type"":{""type"":""array"",""items"":{""type"":""record"",""name"":""Items"",""namespace"":""Customer.Orders"",""fields"":[{""name"":""quantity"",""type"":""int""},{""name"":""Name"",""type"":""string""}]}}}]}");
		private string _orderNumber;
		private string _status;
		private IList<Customer.Orders.Items> _orderItems;
		public virtual Schema Schema
		{
			get
			{
				return CustomerOrder._SCHEMA;
			}
		}
		public string orderNumber
		{
			get
			{
				return this._orderNumber;
			}
			set
			{
				this._orderNumber = value;
			}
		}
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				this._status = value;
			}
		}
		public IList<Customer.Orders.Items> orderItems
		{
			get
			{
				return this._orderItems;
			}
			set
			{
				this._orderItems = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.orderNumber;
			case 1: return this.status;
			case 2: return this.orderItems;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.orderNumber = (System.String)fieldValue; break;
			case 1: this.status = (System.String)fieldValue; break;
			case 2: this.orderItems = (IList<Customer.Orders.Items>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
