name: pack.nuget.yml
on:
  release:
    types:
      - published
      - edited

  #workflow_dispatch:
  # inputs:
  #  enableManualDeployement :
  #    description: 'Click to enable manual deployment from a custom branch to the test environment.'
  #    default: false
  #    required: true
  #    type: boolean

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
   
    - name: Check semantic version
      id: checksemver
      run: |
            if [[ ${GITHUB_REF} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]+$ ]] 
                      then
                           echo "IsSemanticVersion=true" >> $GITHUB_OUTPUT
            elif [[ ${GITHUB_REF} =~ ^refs/tags/[0-9]+\.[0-9]+\.[0-9]-[a-z]+$ ]] 
                      then
                           echo "IsSemanticVersion=true" >> $GITHUB_OUTPUT
            else
                          
                           echo "IsSemanticVersion=false" >> $GITHUB_OUTPUT
                           echo "Release Tag does not follow semantic versioning"
                           exit 1;
                          
            fi
  publish:
    needs: semver
    if: ${{ needs.semver.steps.checksemver.outputs.IsSemanticVersion }}=='true'
    env:
      solution: '${{ github.workspace }}/Nucleotidz.Kafka.Consumer.sln'
      feedurl : 'https://nuget.pkg.github.com/nucleo-tidz/index.json'
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Set version variable from tag
      run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV    

    - name: Restore dependencies
      run: dotnet restore $solution

    - name: Build
      run: dotnet build $solution /p:Version=${version} --no-restore

    - name: Publish
      if: github.event_name == 'release'
      run: nuget push **\*.${version}.nupkg -Source $feedurl  -SkipDuplicate -ApiKey ${{ secrets.GITHUB_TOKEN }}
